### ISSUE TITLE
Image error.

### ISSUE THREAD

**Issue by avisheksanvas** [TheLycaeum/pygame#3]
The images are not being loaded. It is showing this error :
pygame.error: File is not a Windows BMP file .
I'm on macOS Sierra 10.12

**Comment by nibrahim** [comment]
Can't really help without a complete traceback and details. Don't know whether the version of sdlimage which you have supports png files.

**Comment by avisheksanvas** [comment]
This is the traceback : 
`Traceback (most recent call last):
  File "game.py", line 365, in <module>
    main()
  File "game.py", line 260, in main
    ship = ShipSprite(everything, weapon_fire)
  File "game.py", line 166, in __init__
    self.image = pygame.image.load("ship.png").convert_alpha()
pygame.error: File is not a Windows BMP file
`

**Comment by nibrahim** [comment]
Looks like your libsdl-image doesn't support pngs. You can either convert the png files in the repo to bmp and fix the path names. or you can upgrade your SDLimage to work with the png files.

**Comment by avisheksanvas** [comment]
I'll try it out. Thanks a ton! 😀
